name: Upload docker image to dockerhub

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Build image
      run: docker build -t ${{ vars.DOCKER_USERNAME }}/libery-app .
    
    - name: docker upload image 
      run: docker push ${{ vars.DOCKER_USERNAME }}/libery-app

      
      

       
